services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - .:/var/www
            - ./logs/php.log:/var/log/fpm-php.www.log
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9000:9000"
        expose:
            - "9000"
        networks:
            - brand-listing-network
        depends_on:
            - db
            - nginx
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        ports:
            - "3000:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - brand-listing-network
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        ports:
            - "8080:80"
        networks:
            - brand-listing-network
        volumes:
            - .:/var/www
            - ./logs/nginx:/var/log/nginx/

networks:
    brand-listing-network:
        driver: bridge

volumes:
    db_data:
        driver: local
