name: CI Pipeline

on:
  push:
    branches: ["master", "develop", "Base-seteup-with-docker", write-unit-tests]
  pull_request:
    branches: [master", "develop", "Base-seteup-with-docker", write-unit-tests]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build project for tests
        if: |
          github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/Base-seteup-with-docker'||
          github.ref == 'refs/heads/write-unit-tests'
        run: |
          make composer
          docker-compose exec -T app php artisan passport:install --force
          make seed

      - name: start mysql
        run: sudo /etc/init.d/mysql start

      - name: Create test database
        run: mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS laravel_test;"

      - name: Run tests on develop branch
        if: |
          github.ref == 'refs/heads/master' ||
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/Base-seteup-with-docker'||
          github.ref == 'refs/heads/write-unit-tests'
        run: make test

      - name: Deploy acceptance
        if: |
          github.ref == 'refs/heads/develop' ||
          github.ref == 'refs/heads/Base-seteup-with-docker'
        run: make deploy-acceptance

      - name: Deploy staging
        if: github.ref == 'refs/heads/release/'
        run: make deploy-staging

      - name: Deploy to production
        if: github.ref == 'refs/heads/master'
        run: make deploy-production
